openapi: 3.0.3
info:
  title: fluxTrack-API
  description: This is the API for the fluxTrack inventory managment software.
  version: 0.0.1
servers:
- url: https://fluxtrack.com/api/v01
tags:
- name: inventorylist
  description: Available items in inventory
- name: partnerlist
  description: Available partners
paths:
  /inventorylist:
    get:
      tags:
      - inventorylist
      summary: Gets a list of all items in the inventory
      description: Gets a list of all items in the inventory
      operationId: getItems
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      tags:
      - inventorylist
      summary: Add a new item to the inventory
      description: Add a new item to the inventory
      operationId: addItem
      requestBody:
        description: Create new item in inventory
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
            application/xml:
              schema:
                $ref: "#/components/schemas/Item"
        "405":
          description: Invalid input
  /partnerlist:
    get:
      tags:
      - partnerlist
      summary: Gets a list of all partners
      description: Gets a list of all partners
      operationId: getPartner
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Partner"
    post:
      tags:
      - partnerlist
      summary: Add a new partner
      description: Add a new partner
      operationId: addPartner
      requestBody:
        description: Create new Partner
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Partner"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partner"
            application/xml:
              schema:
                $ref: "#/components/schemas/Partner"
        "405":
          description: Invalid input
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        itemName:
          type: string
          example: Puzzle_1000pcs
        itemPrize:
          type: number
          format: number
          example: 49.95
        itemQuantity:
          type: integer
          format: int64
          example: 5
    Partner:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        partnerName:
          type: string
          example: Drachehoeli
        partnerEmail:
          type: string
          example: drachehoeli@example.components
        partnerPhone:
          type: integer
          format: int64
          example: 103102839
        partnerAddress:
          type: array
          items:
            $ref: "#/components/schemas/Address"
    Address:
      type: object
      properties:
        name:
          type: string
          example: Drachehoeli GmbH
        street:
          type: string
          example: Hauptstrasse
        number:
          type: string
          example: 10a
        zip:
          type: integer
          format: int64
          example: 4104
        city:
          type: string
          example: Oberwil
        country:
          type: string
          example: Switzerland
  requestBodies:
    Item:
      description: Item object that needs to be added to the inventory
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Item"
    Partner:
      description: Partner that needs to be added
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Partner"
