spring.application.name=demo
#database config
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## uncomment below line to persist data in a file
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto = update
#spring.h2.console.enabled=true
#security config
jwt.key=mysecretkey-4107-fabarn-rembru-silmei-flostie-4106-fluxTrack-123456789